spring.application.name=Emilly_EcomerceV2
spring.mvc.hiddenmethod.filter.enabled=true
server.port=8080
server.servlet.session.cookie.name=e-shop
server.reactive.session.timeout=15m

spring.main.allow-circular-references=true


spring.web.resources.add-mappings=true
# Пробај со оваа варијанта (најчеста за Gemma)
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview
spring.ai.google.genai.api-key=AIzaSyDwxL7yoD4d_1AD256A9LnnO7kjXM0XJT8

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hristijan.kolevski099@gmail.com
spring.mail.password=fmwm lzwd etvt ejvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=DEBUG

server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.google.client-id=103575189286-rl2mdfqdtf3ttsit7996uk8mlrh1ttq3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#google
spring.security.oauth2.client.registration.google.scope=profile,email
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.redirect-uri=https://api.emilly.mk/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Facebook Client Registration
spring.security.oauth2.client.registration.facebook.client-id=555816220137275
spring.security.oauth2.client.registration.facebook.client-secret=127dcfbf8a8e3228a901102eda124255
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=https://api.emilly.mk/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.facebook.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.facebook.client-name=Facebook

# Facebook Provider Configuration
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v17.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v17.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=id

Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:5173

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=postgres
spring.datasource.password=183061
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# Сесиското колаче да се испраќа само преку HTTPS
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
